NielsenMedia/urls.py
#! /usr/bin/env python
#coding=utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('MediaChooser.NielsenMedia.views',
    (r'^$', 'rank', {'template':'nielsen_media/nielsen_rank.html'}),
    (r'^traffic/$', 'traffic', {'template':'nielsen_media/nielsen_traffic.html'}),
    (r'^overlap/$', 'overlap', {'template':'nielsen_media/nielsen_overlap.html'}),
    (r'^chart/$', 'chart'),
    # Ajax
    (r'^get_media_options/$', 'get_media_options'),
    (r'^get_overlap_data/$', 'get_overlap_data'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
# Example:
# (r'^demo/', include('demo.foo.urls')),

# Uncomment the admin/doc line below and add 'django.contrib.admindocs'
# to INSTALLED_APPS to enable admin documentation:
# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

#url(r'^$', 'MediaChooser.ad_resource_mgmt.views.query', name="query"),
# Uncomment the next line to enable the admin:
(r'^', include('ad_resource_mgmt.urls')),
(r'^admin/(.*)', admin.site.root),
(r'^accounts/', include('registration.urls')),
(r'^weekly-report/', include('media_weekly_report.urls')),

(r'^client/', include('client.urls')),
(r'^media-planning/', include('media_planning.urls')),
(r'^media/', include('media.urls')),
(r'^pr/', include('pr.urls')),
#(r'^nielsen-media/', include('NielsenMedia.urls')),
#(r'^torres/', include('torres.urls')),

)

NielsenMedia/models.py
#! /usr/bin/env python
#coding=utf-8

from django.db import models

class NielsenCategory (models.Model):

    parent = models.ForeignKey('self', related_name='parent_category', verbose_name=u'上级分类', blank=True, null=True)
    c_name = models.CharField('中文名称', max_length=40, help_text='中文名称')
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称')
    desc = models.TextField('描述', blank=True, null=True, help_text='描述')
    
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'
        unique_together = (("c_name", "e_name"),)
        
    def __unicode__(self):
        if self.parent == None:
            return self.c_name
        else:
            return self.parent.c_name+'->'+self.c_name


class NielsenMedia (models.Model):

    domain = models.URLField('域名',verify_exists=False)
    c_name = models.CharField('中文名称', max_length=40, help_text='中文名称')
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称')
    main_category = models.ForeignKey(NielsenCategory, related_name='media_main_category', verbose_name='所属分类', blank=True, null=True)
    sub_category = models.ForeignKey(NielsenCategory, related_name='media_sub_category', verbose_name='所属子分类', blank=True, null=True)
    
    class Meta:
        verbose_name = 'Nielsen媒体'
        verbose_name_plural = 'Nielsen媒体'
        
    def __unicode__(self):
        return self.c_name


class NielsenChannel (models.Model):

    media = models.ForeignKey(NielsenMedia, verbose_name='所属媒体', blank=True, null=True)
    domain = models.URLField('域名',verify_exists=False)
    c_name = models.CharField('频道中文名称', max_length=40, help_text='中文名称')
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称')
    main_category = models.ForeignKey(NielsenCategory, related_name='channel_main_category', verbose_name='所属分类', blank=True, null=True)
    sub_category = models.ForeignKey(NielsenCategory, related_name='channel_sub_category', verbose_name='所属子分类', blank=True, null=True)
    
    class Meta:
        verbose_name = 'Nielsen频道'
        verbose_name_plural = 'Nielsen频道'
        
    def __unicode__(self):
        return self.c_name

class Province (models.Model):

    c_name = models.CharField('中文名称', max_length=40, help_text='中文名称', unique=True)
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称', unique=True)
    
    class Meta:
        verbose_name = '省份'
        verbose_name_plural = '省份'
        
    def __unicode__(self):
        return self.c_name

class NielsenTrafficData(models.Model):

    media = models.ForeignKey(NielsenMedia, verbose_name='媒体', blank=True, null=True)
    channel = models.ForeignKey(NielsenChannel, verbose_name='频道', blank=True, null=True)
    province = models.ForeignKey(Province, verbose_name='省份')
    all_ub = models.FloatField(blank=True, null=True)
    all_us_change = models.FloatField(blank=True, null=True)
    all_ts = models.FloatField(blank=True, null=True)
    all_ub_freq = models.FloatField(blank=True, null=True)
    all_asd = models.FloatField(blank=True, null=True)
    sample_ub = models.FloatField(u'样本流量UB(mil.)')
    sample_ub_freq = models.FloatField(u'样本流量UB Freq')
    sample_ts = models.FloatField(u'样本流量TS(mil.)')
    sample_asd = models.FloatField(u'样本流量ASD(s)')
    week = models.DateTimeField(u'周', max_length=40)

    class Meta:
        verbose_name = 'Nielsen流量数据'
        verbose_name_plural = 'Nielsen流量数据'

    def __unicode__(self):
        if self.media:
            return self.media.c_name + '-' + self.province.c_name + '-' + str(self.week.year) + str(self.week.month) + str(self.week.day)
        elif self.channel:
            return self.channel.c_name + '-' + self.province.c_name + '-' + str(self.week.year) + str(self.week.month) + str(self.week.day)
            
class NielsenOverlap (models.Model):

    media_a = models.ForeignKey(NielsenMedia, related_name='media_a', verbose_name='基准媒体')
    media_b = models.ForeignKey(NielsenMedia, related_name='media_b', verbose_name='对比媒体')
    net_ub = models.FloatField(u'Net UB(mil.)')
    ub_dup = models.FloatField(u'UB Dup(mil.)')
    dup = models.FloatField(u'重合度Dup(%)')
    week = models.DateTimeField(u'周', max_length=40)
    
    class Meta:
        verbose_name = 'Nielsen媒体重合度'
        verbose_name_plural = 'Nielsen媒体重合度'
        
    def __unicode__(self):
        return "%s - %s: %s" % (self.media_a, self.media_b, self.dup)

NielsenMedia/forms.py
#! /usr/bin/env python
#coding=utf-8

from django import forms
from MediaChooser.NielsenMedia.models import *
from django.contrib.admin import widgets

def _get_weeks():
    from django.db import connection
    cursor = connection.cursor()
    qs = cursor.execute('SELECT DISTINCT week FROM "NielsenMedia_nielsenoverlap" ORDER BY "week" DESC')
    qs = cursor.fetchall()
    weeks = [(str(q[0]).split(' ')[0],str(q[0]).split(' ')[0]) for q in qs]
    return weeks
    
class NielsenRankForm(forms.ModelForm):
    
    #category = forms.ModelChoiceField('ss',queryset=NielsenCategory.objects.all())
    #NielsenCategory = forms.ModelChoiceField('ss', queryset=NielsenCategory.objects.all())
    #category = forms.ChoiceField(choices=(('-','-'),))
    category = forms.ModelChoiceField(label='Category', queryset=NielsenCategory.objects.filter(parent=None))
    media = forms.ModelChoiceField(label='Media', queryset=NielsenMedia.objects.all())
    week = forms.DateField(label='week', widget=widgets.AdminDateWidget)
    province = forms.ModelChoiceField(label='province', queryset=Province.objects.all())

    class Meta:
        model = NielsenTrafficData
        #exclude = ('responsible_user', 'create_time', 'last_modified', 'can_modify')
        
class NielsenOverlapForm(forms.ModelForm):
    
    category_base = forms.ModelChoiceField(label='Category', queryset=NielsenCategory.objects.filter(parent=None))
    category_comp = forms.ModelChoiceField(label='Category', queryset=NielsenCategory.objects.filter(parent=None))
    
    weeks = _get_weeks()
    week = forms.ChoiceField(label='week', choices= weeks)
    
    class Meta:
        model = NielsenOverlap
        
class NielsenTrafficForm (forms.ModelForm):

    category = forms.ModelChoiceField(label='Category', queryset=NielsenCategory.objects.filter(parent=None))
    weeks = _get_weeks()
    week_start = forms.ChoiceField(label='week', choices= weeks)
    week_end = forms.ChoiceField(label='week', choices= weeks)
    class Meta:
        model = NielsenTrafficData
        

NielsenMedia/views.py
import datetime

from django.shortcuts import render_to_response, get_object_or_404
from django.utils import simplejson
from django.http import HttpResponse

from MediaChooser.NielsenMedia.models import NielsenCategory, NielsenMedia, NielsenOverlap, NielsenTrafficData, Province
from MediaChooser.NielsenMedia.forms import NielsenRankForm, NielsenTrafficForm, NielsenOverlapForm

def rank(request, template):
    if request.method == 'POST':
        form = NielsenRankForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = NielsenRankForm()
    return render_to_response(template, locals())

def traffic(request, template):
    if request.method == 'POST':
        form = NielsenTrafficForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = NielsenTrafficForm()
    return render_to_response(template, locals())

def overlap(request, template):
    if request.method == 'POST':
        form = NielsenOverlapForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = NielsenOverlapForm()
        
    return render_to_response(template, locals())

def get_overlap_data(request):
    get = request.GET
    data = {}
    if get.has_key('base_media') and get.has_key('comp_media') and get.has_key('week'):
        base_media = get_object_or_404(NielsenMedia, pk=int(get['base_media']))
        p = Province.objects.get(e_name = 'all')
        week = get['week'] + ' 00:00:00'
        data['overlap'] = []
        for c in get['comp_media'].split(','):
            comp_media = get_object_or_404(NielsenMedia, pk=int(c))
            ntd = NielsenTrafficData.objects.get(media= comp_media, week= week, province = p)
            no = NielsenOverlap.objects.get(media_a= base_media, media_b= comp_media, week= week)
            data['overlap'].append({'c_name': comp_media.c_name, 'sample_ub': ntd.sample_ub, 'net_ub': no.net_ub, 'ub_dup': no.ub_dup, 'dup': no.dup})
        
        ntd_base = NielsenTrafficData.objects.get(media= base_media, week= week, province = p)
        data['media_c_name'] = base_media.c_name
        data['sample_ub'] = ntd_base.sample_ub
        data['sample_ub_freq'] = ntd_base.sample_ub_freq
        data['sample_ts'] = ntd_base.sample_ts
        data['sample_asd'] = ntd_base.sample_asd
        
        return HttpResponse(simplejson.dumps(data))

def get_media_options(request):
    get = request.GET
    if get.has_key('category'):
        c = get_object_or_404(NielsenCategory, pk=int(get['category']))
        media = NielsenMedia.objects.filter(main_category= c)
        data = [{'caption': m.c_name, 'value': m.id} for m in media]
        return HttpResponse(simplejson.dumps(data))
    
def chart(request):
    from MediaChooser.NielsenMedia.chart import chart
    return HttpResponse(chart.create(), mimetype="application/json")

templates/nielsen_media/nielsen_media_base.html
{% extends "base.html" %}

{% block extrahead %}

    <link href="/media/css/forms.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media_ldf/css/demos.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media_ldf/css/mc.css" rel="stylesheet" type="text/css" media="screen" />

    <script type="text/javascript" src="/media_ldf/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/media_ldf/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/media_ldf/js/jquery.validate.min.js"></script>

    <script type="text/javascript" src="../../admin/jsi18n/"></script>
    <script type="text/javascript" src="/media/js/core.js"></script>
    <script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/media/js/calendar.js"></script>
    <script type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>
{% endblock %}

{% block header %}
MediaChooser <a href="{% url MediaChooser.NielsenMedia.views.rank %}">Nielsen第三方数据</a>
			<p style="font-weight:bold;">{% if user.is_authenticated %}Welcome, {% if user.last_name %}{{ user.last_name }}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}
			<a href="{% url django.contrib.auth.views.logout %}"> 登出 </a>{% else %}欢迎您，请<a href="{% url django.contrib.auth.views.login %}"> 登录 </a>{% endif %}{% if user.is_authenticated %} | <a href="{% url django.contrib.auth.views.password_change %}"> 修改密码 </a>{% endif %}</p>	
{% endblock %}


{% block columnwrap %}
     <ul>    
        <li><a href="{% url MediaChooser.NielsenMedia.views.rank %}">网站排名查询</a></li>
        <li><a href="{% url MediaChooser.NielsenMedia.views.traffic %}">流量趋势分析</a></li>
        <li><a href="{% url MediaChooser.NielsenMedia.views.overlap %}">媒体重合度分析</a></li>
    </ul>
    
    <div id="content-main">
        {% block content %}{% endblock %}
    </div>

{% endblock %}

templates/nielsen_media/nielsen_overlap.html
{% extends "nielsen_media/nielsen_media_base.html" %}

{% block content %}

	<p>媒体重合度分析:</p>

	<form action="" method="POST" id="form_overlap">
		<p>{{ form.category_base.errors }}<label for="id_category_base">基准媒体: </label>{{ form.category_base }}
			<select id="mediadropdown_base" disabled="disabled" name="mediadropdown_base"><option value="---">---</option></select>
		</p>

		<p>{{ form.category_comp.errors }}<label for="id_category_comp">对比媒体: </label>{{ form.category_comp }}
			<select id="mediadropdown_comp" disabled="disabled" name="mediadropdown_comp"><option value="---">---</option></select>
			<input id="button_add_media" type="button" value="增加">
			<input id="button_empty_media" type="button" value="清空">
		</p>
		<p>
			对比媒体列表:<span id="compmedialist"></span>
		</p>
		<p>{{ form.week.errors }}<label for="id_week">周: </label>{{ form.week }}</p>
		<p>
			<input id="button_chart" type="button" value="生成图表">
		</p>
	</form>
	

	<p id='p_base_media'></p>
	
	<div id="items_table"></div>
	<!-- <table cellpadding="0" cellspacing="0" border="0" class="display" id="items_table">
    <thead>
		<tr>
            <th>名称</th>
            <th>样本流量 UB(mil.)</th>
            <th>UB Dup(mil.)</th>
            <th>Net UB(mil.)</th>
            <th>Dup %</th>
        </tr>
    </thead>
    <tbody id='items_table_tbody' >
        {% for item in items %}
            <tr>
			<td>{{ item.c_name }}</td>
			<td>{{ item.sample_ub }}</td>
            <td>{{ item.sample_ts }}</td>
            <td>{{ item.sample_ub_freq }}</td>
            <td>{{ item.sample_asd}}</td>
            </tr>
        {% endfor %} 
    </tbody>
	</table> -->
{% endblock %}

{% block js %}
<SCRIPT LANGUAGE="JavaScript">

$(document).ready(function(){
	
	$("select[id^='id_category']").change(function(){
		adjustMediaDropdown($(this).attr('id'));
	});
	
	var media_list = new Array();

	function has_element(array, value){
		var i;
		for (i=0; i<array.length; i++)
		{
			if (array[i] == value)
			{
				return true;
			}
		}
		return false;
	}

	$("#button_add_media").click(function(){
		
		var base_media = $('#mediadropdown_base').val();
		var comp_media = $('#mediadropdown_comp').val();
		if (base_media == null || base_media == '---'){
			alert("请选择基准媒体");
			return false;
		}
		if (comp_media == null || comp_media == '---'){
			alert("请选择对比媒体");
			return false;
		}

		var value = $('#mediadropdown_comp').val();
		if (has_element(media_list, value)){
			alert('已经添加此媒体');
			return false;
		}else {
			media_list.push(value);
			var caption = $("select[id='mediadropdown_comp'] option[value="+comp_media+"]").text();
			$('#compmedialist').append(caption+' ');
		}
	});

	$("#button_empty_media").click(function(){
		$('#compmedialist').empty();
		media_list.length = 0;
	});

	$.fn.emptySelect = function() {
		return this.each(function(){
		if (this.tagName=='SELECT') this.options.length = 0;
		});
	}

	$.fn.loadSelect = function(optionsDataArray) {
		return this.emptySelect().each(function(){
		if (this.tagName=='SELECT') {
		var selectElement = this;
		$.each(optionsDataArray,function(index,optionData){
			var option = new Option(optionData.caption, optionData.value);
			if ($.browser.msie) {
				selectElement.add(option);
			}else {
				selectElement.add(option,null);
			}
			});
			}
		});
		}

	$("#button_chart").click(function(){
		base_media = $('#mediadropdown_base').val();
		path = location.pathname.split('/');
		path[path.length-2] = 'get_overlap_data';
		table_data =  new Array();
		week = $("#id_week").attr("value");

		$.getJSON(path.join('/'), {base_media: base_media, 'comp_media':media_list.toString(), week: week}, function(data){
			
			$('.top').remove();
			$('#items_table_paginate').remove();
			$('.dataTables_paginate').remove();
			for (i=0; i<data.overlap.length; i++)
			{
				table_data[i] = new Array();
				table_data[i].push(data.overlap[i].c_name, data.overlap[i].sample_ub, data.overlap[i].net_ub, data.overlap[i].ub_dup, data.overlap[i].dup);
			}
			$("#p_base_media").empty();
			$("#p_base_media").append("<p>基准媒体</p><table cellpadding='0' cellspacing='0' border='0' class='display'><tr><td>名称</td><td>样本流量 UB(mil.) </td><td>样本流量 TS(mil.)</td><td>样本流量 UB Freq</td><td>样本流量 ASD(s)</td></tr><tr><td>"+data.media_c_name+"</td><td>"+ data.sample_ub +"</td><td>"+data.sample_ub_freq+"</td><td>"+ data.sample_ts +"</td><td>"+data.sample_asd+"</td></tr></table><hr><p>对比媒体</p>");

			items_table = $("#items_table").dataTable({      		
					'aaData': table_data,

					"aoColumns": [
						{ "sTitle": "名称" , "sWidth": "10%"},
						{ "sTitle": "样本流量 UB(mil.)" , "sWidth": "20%"},
						{ "sTitle": "UB Dup(mil.)" , "sWidth": "20%"},
						{ "sTitle": "Net UB(mil.)" , "sWidth": "20%"},
						{ "sTitle": "Dup %" , "sWidth": "20%"}
					],
            		"sDom": '<"top"if>ptrp'
            	});
		});
	});
	});

	function adjustMediaDropdown(select_id){
		var category = $('#'+select_id).val();
		var media_dropdown;
		if (select_id == 'id_category_base'){
			media_dropdown = $('#mediadropdown_base');
		}else if (select_id == 'id_category_comp'){
			media_dropdown = $('#mediadropdown_comp');
		}
		if (category.length == 0){
			media_dropdown.attr("disabled", true);
			$(media_dropdown).emptySelect();
		}else{
			media_dropdown.attr("disabled", false);
			path = location.pathname.split('/');
			path[path.length-2] = 'get_media_options'
			$.getJSON(path.join('/'), {category:category}, function(data){
				media_dropdown.loadSelect(data);
			});
		}}
	
</SCRIPT>
{% endblock %}

templates/nielsen_media/nielsen_rank.html
{% extends "nielsen_media/nielsen_media_base.html" %}

{% block content %}

<p>网站排名查询:</p>

<form action="" method="POST" id="form_nielsen">
	<p>{{ form.category.errors }}<label for="id_category">分类: </label>{{ form.category }}
	<select id="mediadropdown" disabled="disabled" name="mediadropdown"><option value="---">---</option></select>
	</p>
	<p>{{ form.province.errors }}<label for="id_province">省份: </label>{{ form.province }}</p>
	<!-- <p>{{ form.media.errors }}<label for="id_media">网站: </label>{{ form.media }}</p> -->
	<p>{{ form.week.errors }}<label for="id_week">周: </label>{{ form.week }}</p>

	<input type="submit" value="查询" />
</form>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="items_table">
    <thead>
        <tr>
            <th>排名</th>
            <th>中文名</th>
            <th>域名</th>
            <th>样本流量(TS)</th>
            <th>样本流量(UB)</th>
            <th>样本流量(Freq)</th>
            <th>样本流量(ASD)</th>
        </tr>
    </thead>
    <tbody id='items_table_tbody' >
        {% for item in items %}
            <tr>
				<td>{{ item.rank }}</td>
                <td>{{ item.c_name }}</td>
                <td>{{ item.domain }}</td>
                <td>{{ item.ts }}</td>
                <td>{{ item.sample_ts }}</td>
                <td>{{ item.sample_ub_freq }}</td>
                <td>{{ item.sample_asd}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block js %}
<SCRIPT LANGUAGE="JavaScript">

$(document).ready(function(){
	
	$('#id_category').change(function(){
		adjustMediaDropdown()
	});

	$.fn.emptySelect = function() {
		return this.each(function(){
	    if (this.tagName=='SELECT') this.options.length = 0;
	  });
	}

	$.fn.loadSelect = function(optionsDataArray) {
		return this.emptySelect().each(function(){
		if (this.tagName=='SELECT') {
		var selectElement = this;
		$.each(optionsDataArray,function(index,optionData){
			var option = new Option(optionData.caption, optionData.value);
			if ($.browser.msie) {
				selectElement.add(option);
			}else {
				selectElement.add(option,null);
			}
			});
			}
		});
		}

	report_item_table = $("#items_table").dataTable({
            		"bPaginate": true,
                    "iDisplayLength": 20,
                    "bSort": true,
            		"bInfo": true,
            		"bLengthChange": false,
            		"aoColumns": [{"sType":"string"}, {"sType":"string"}, null, null, null, null, null], /*null{"bSearchable": false, "bSortable": false}, {"bSearchable": false, "bSortable": false}],*/
            		"oLanguage": {
            			"sInfo": "共 _TOTAL_ 条周报",
            			"sInfoFiltered": "(从 _MAX_ 条周报中过滤获得)",
            			"sSearch": "搜索",
                        "sInfoEmpty": "共 0 个文件/文件夹",
                        "sZeroRecords": "无匹配项" 
            		},
            		"sDom": '<"top"if>ptrp'
            	});

	});

	function adjustMediaDropdown(){
		var category = $('#id_category').val();
		var media_dropdown = $('#mediadropdown');
		if (category.length == 0){
			media_dropdown.attr("disabled", true);
			$(media_dropdown).emptySelect();
		}else{
			media_dropdown.attr("disabled", false);
			path = location.pathname + 'get_media_options/'
			$.getJSON(path, {category:category}, function(data){
				media_dropdown.loadSelect(data);
			});
		}}
</SCRIPT>
{% endblock %}

templates/nielsen_media/nielsen_traffic.html
{% extends "nielsen_media/nielsen_media_base.html" %}

{% block content %}

	<p>流量趋势分析:</p>

	<form action="" method="POST" id="form_nielsen">

		<p>{{ form.category.errors }}<label for="id_category">网站: </label>{{ form.category }}
			<select id="mediadropdown" disabled="disabled" name="mediadropdown"><option value="---">---</option></select>
		</p>

		<p>{{ form.week_start.errors }}<label for="id_week_start">从: </label>{{ form.week_start }}&nbsp;&nbsp;{{ form.week_end.errors }}<label for="id_week_end">到: </label>{{ form.week_end }}</p>

		<p>
			<input id="button_chart" type="button" value="生成图表">
		</p>
	</form>
	
	<div id="jshere"> </div>

	<div id="my_chart"></div>
	
{% endblock %}


{% block js %}
<script type="text/javascript" src="/files_dl/swfobject.js"></script>

<SCRIPT LANGUAGE="JavaScript">

$(document).ready(function(){
	
	$("select[id^='id_category']").change(function(){
		adjustMediaDropdown();
	});

	$.fn.emptySelect = function() {
		return this.each(function(){
		if (this.tagName=='SELECT') this.options.length = 0;
		});
	}

	$.fn.loadSelect = function(optionsDataArray) {
		return this.emptySelect().each(function(){
		if (this.tagName=='SELECT') {
		var selectElement = this;
		$.each(optionsDataArray,function(index,optionData){
			var option = new Option(optionData.caption, optionData.value);
			if ($.browser.msie) {
				selectElement.add(option);
			}else {
				selectElement.add(option,null);
			}
			});
			}
		});
		}

	$('#button_chart').click(function(){
		$("#jshere").empty();
		path = location.pathname.split('/');
		path[path.length-2] = 'chart';
		$("#jshere").append("<script type='text/javascript'>swfobject.embedSWF('/files_dl/open-flash-chart.swf', 'my_chart', '500', '300', '9.0.0','expressInstall.swf', {'data-file': path.join('/')}, false, false);<\/script>");
	});

	});

	function adjustMediaDropdown(){
		var category = $("select[id^='id_category']").val();
		var media_dropdown;
		media_dropdown = $('#mediadropdown');
		if (category.length == 0){
			media_dropdown.attr("disabled", true);
			$(media_dropdown).emptySelect();
		}else{
			media_dropdown.attr("disabled", false);
			path = location.pathname.split('/');
			path[path.length-2] = 'get_media_options'
			$.getJSON(path.join('/'), {category:category}, function(data){
				media_dropdown.loadSelect(data);
			});
		}}
	
</SCRIPT>
{% endblock %}