media_planning/urls.py
#! /usr/bin/env python
#coding=utf-8

from django.conf.urls.defaults import *

from MediaChooser.media_planning.views import *

urlpatterns = patterns('',
    (r'^upload/$', upload),
    (r'^my-uploads/$', my_uploads),
    (r'^uploads-checkout/$', uploads_checkout),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
# Example:
# (r'^demo/', include('demo.foo.urls')),

# Uncomment the admin/doc line below and add 'django.contrib.admindocs'
# to INSTALLED_APPS to enable admin documentation:
# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

#url(r'^$', 'MediaChooser.ad_resource_mgmt.views.query', name="query"),
# Uncomment the next line to enable the admin:
(r'^', include('ad_resource_mgmt.urls')),
(r'^admin/(.*)', admin.site.root),
(r'^accounts/', include('registration.urls')),
(r'^weekly-report/', include('media_weekly_report.urls')),

(r'^client/', include('client.urls')),
(r'^media-planning/', include('media_planning.urls')),
(r'^media/', include('media.urls')),
(r'^pr/', include('pr.urls')),
#(r'^nielsen-media/', include('NielsenMedia.urls')),
#(r'^torres/', include('torres.urls')),

)

ad/models.py
#! /usr/bin/env python
#coding=utf-8

import datetime

from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User

from MediaChooser.media.models import Media, Channel
from MediaChooser.client.models import Client

EFFECTIVE_COUNT = 10
DC_CLICK_EVENTTYPE = 4

# 广告形式表
class AdType(models.Model):
    AD_CATEGORY_CHOICES = ((1, '硬广'),(2, '软广'),(3, '专题'),(4, '活动'),)

    category = models.PositiveSmallIntegerField('分类', choices=AD_CATEGORY_CHOICES, help_text='分类')
    c_name = models.CharField('中文名称', max_length=40, help_text='中文名称')
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称', blank=True, null=True)
    desc = models.TextField('描述', blank=True, null=True, help_text='描述')
    demo = models.FileField('演示', upload_to='files/', blank=True, null=True, help_text='演示')
    advantage = models.TextField('优势', blank=True, null=True, help_text='优势')
    disadvantage = models.TextField('劣势', blank=True, null=True, help_text='劣势')
    class Meta:
        verbose_name = '广告形式'
        verbose_name_plural = '广告形式'
    def __unicode__(self):
        return self.c_name

# 投放类型
class ActivityType(models.Model):
    name = models.CharField('名称', max_length=20, help_text='活动名称')
    desc = models.TextField('描述', null=True, blank=True, help_text='描述')

    class Meta:
        verbose_name = '活动类型'
        verbose_name_plural = '活动类型'
    
    def __unicode__(self):
        return self.name

class Ad(models.Model):
    client   = models.ForeignKey(Client, verbose_name='广告主')
    #adtype = models.ForeignKey(AdType, verbose_name='类型', related_name='related_adinfo')
    activity_type = models.ForeignKey(ActivityType)
    #product  = models.ForeignKey(Product)
    #minisite = models.ForeignKey(MiniSite)
    DE_campaign_id = models.IntegerField('campaign_id', unique=True, help_text='campaign_id')
    name  = models.CharField('name', help_text='name', max_length=256)

    # statistic related info
    spending	= models.IntegerField('投放费用', default=0)
    click		= models.IntegerField('DE记录到的点击数', default=0)
    cpc			= models.FloatField('CPC', default=0)

    #title = models.CharField('title', help_text='title', max_length=96)
    desc = models.TextField('desc', blank=True, null=True, help_text='desc')

    #targeting = models.DateField()
    uploader  = models.ForeignKey(User, verbose_name='上传者')
    start_day = models.DateField('开始日期', help_text='开始日期')
    end_day = models.DateField('结束日期', help_text='结束日期')
    create_time = models.DateTimeField('创建日期', auto_now_add=True, null=True, help_text='创建日期')
    last_modified = models.DateTimeField('最后修改', auto_now=True, null=True, help_text='最后修改')

    related_staff = models.ManyToManyField(User, related_name='ads', verbose_name='相关人员', through='AdRelatedStaff')
    ga_pid = models.CharField('GA profile id', blank=True, max_length=20)
    
    group_id = models.IntegerField('用户组', default=-1)
    
    date_range = []
    media = []
    date_price = {}
    date_click = {}
    
    has_init = False
    
    class Meta:
        verbose_name = 'Campaign'
        verbose_name_plural = 'Campaign'
                    
    def __unicode__ (self):
        return self.name
    
    def _init(self):
        self.date_range = []
        for n in range((self.end_day - self.start_day).days+1):
            date_str = str(self.start_day + datetime.timedelta(days=n))
            self.date_range.append(date_str)
            self.date_price[date_str] = 0
            self.date_click[date_str] = 0
        
        self.media = self._campaign_media()
        
    
    def _campaign_media(self):
        media = set()
        for f in self.flights.all():
            media.add(f.media.c_name)
        media_list = list(media)
        media_list.sort()
        return media_list
    
    def media_click(self):
        """ return sorted media click list during this campaign """
        media_click = {}
        flights = self.flights.all()
        for f in flights:
            if f.media.c_name in media_click:
                media_click[f.media.c_name] += f.click
            else:
                media_click[f.media.c_name] = f.click
        #return [ x[1] for x in sorted(media_click.iteritems(), key=lambda d:d[0])]
        return media_click
    
    def media_price(self):
        """ return sorted media price and tracked price list during this campaign """
        media_price = {}
        media_price_tracked = {}
        flights = self.flights.all()
        for f in flights:
            media_name = f.media.c_name
            if f.if_buy:
                if media_name in media_price:
                    media_price[media_name] += f.total_price * f.discount_after_discount
                else:
                    media_price[media_name] = f.total_price * f.discount_after_discount
                if media_name in media_price_tracked:
                    media_price_tracked[media_name] += f.total_price_tracked * f.discount_after_discount
                else:
                    media_price_tracked[media_name] = f.total_price_tracked * f.discount_after_discount
            else:
                if media_name not in media_price:
                    media_price[media_name] = 0
                if media_name not in media_price_tracked:
                    media_price_tracked[media_name] = 0
        #return [x[1] for x in sorted(media_price.iteritems(), key=lambda d:d[0])], [x[1] for x in sorted(media_price_tracked.iteritems(), key=lambda d:d[0])]
        return media_price, media_price_tracked
    
    def media_cpc(self):
        """ return sorted media cpc list during this campaign """
        media = self.media
        media_cpc = {}
        media_click = self.media_click()
        media_price = self.media_price()[1]
        #for i, m in enumerate(media):
        #    if media_click[i] != 0:
        #        media_cpc[i] = media_price[i] * 1.0 / media_click[i]
        #    else:
        #        media_cpc[i] = 0 
        
        for m in media_price:
            if media_click[m] != 0:
                media_cpc[m] = media_price[m] * 1.0 / media_click[m]
            else:
                media_cpc[m] = 0
        
        return media_cpc
        
    def daily_click(self):
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT date,sum(eventcount) FROM media_planning_de_clickdata \
            WHERE flight_id in %s and eventtype=%s and eventcount > %s\
            GROUP BY date ORDER BY date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            d = str(r[0])
            if d >= str(self.start_day) and d <= str(self.end_day):
                self.date_click[str(r[0])] = r[1]
        
        #return [x[1] for x in sorted(self.date_click.iteritems(), key=lambda d:d[0])]
        return self.date_click
        
    def daily_price(self):
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()        
        sql = "SELECT a.date,sum(b.unit_price * b.discount_after_discount) \
            FROM media_planning_de_clickdata a, media_planning_flight b \
            WHERE a.flight_id in %s AND a.if_planned_spending = true AND a.eventtype=%s AND a.eventcount > %s AND a.flight_id = b.id \
            AND b.if_buy = true GROUP BY a.date ORDER BY a.date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            self.date_price[str(r[0])] = r[1]
        
        #return [x[1] for x in sorted(self.date_price.iteritems(), key=lambda d:d[0])]
        return self.date_price
    
    def daily_cpc(self):
        daily_price = self.daily_price()
        daily_click = self.daily_click()
        #daily_cpc = [0] * len(self.date_range)
        daily_cpc = {}
        #for i in range(len(daily_cpc)):
        #    if daily_click[i] != 0:
        #        daily_cpc[i] = daily_price[i] / daily_click[i]
        #    else:
        #        daily_cpc[i] = 0
        for d in daily_click:
            if daily_click[d] != 0:
                daily_cpc[d] = daily_price[d] / daily_click[d]
            else:
                daily_cpc[d] = None
        return daily_cpc
    
    def media_daily_click(self):
        media_daily_click = {}
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT b.c_name, a.date, sum(eventcount) FROM media_planning_de_clickdata a, media_media b \
            WHERE flight_id in %s and eventtype=%s and eventcount > %s and a.media_id = b.id \
            GROUP BY b.c_name, date ORDER BY b.c_name, date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            media_name = r[0]
            date = r[1]
            click = r[2]
            
            if media_name in media_daily_click:
                media_daily_click[media_name][str(date)] = r[2]
            else:
                media_daily_click[media_name] = [0] * len(self.date_range)
        
        return media_daily_click
        #
    
    def campaign_detail(self):
        from django.db import connection
        cursor = connection.cursor()
        sql = "select b.c_name, d.c_name, c.adform, a.total_price * a.discount_after_discount, \
                a.click, a.if_buy, a.start_day, a.end_day, a.\"DE_ad_id\" \
                from media_planning_flight a, media_media b, media_mediaadinfo c, media_channel d \
                where a.media_id = b.id and a.ad_id =%s and c.id = a.media_ad_info_id and \

media_planning/models.py
#! /usr/bin/env python
#coding=utf-8
import datetime

from django.db import models
from MediaChooser.ad.models import Ad
from MediaChooser.media.models import MediaAdInfo, Media, Channel

# Create your models here.

class Flight(models.Model):
    ad             = models.ForeignKey(Ad, verbose_name='campaign', help_text='campaign', related_name='flights')

    media = models.ForeignKey(Media, verbose_name='Media', related_name='flights')
    channel = models.ForeignKey(Channel, verbose_name='Channel', related_name='flights')
    media_ad_info  = models.ForeignKey(MediaAdInfo, verbose_name='MediaAdInfo', help_text='MediaAdInfo', related_name='flights')

    pv				= models.IntegerField('PV', help_text='Page View', blank=True, null=True)
    spending      	= models.IntegerField('投放量', help_text='投放量') # 排期上写的投放量
    unit = models.CharField('单位', max_length=8, help_text='单位') # 投放的单位，CPM/天
    ad_days = models.SmallIntegerField('投放天数', help_text='投放天数') # 从排期中获取到的投放的总天数
    ad_days_tracked = models.SmallIntegerField('有效投放天数', help_text='有效投放天数', default=0)	# 有效的投放天数，也即监测到的点击数>10的那些投放日
    if_buy		   = models.BooleanField('购买方式', help_text='购买方式')	# True：购买；False：赠送
    discount       = models.FloatField('折扣', help_text='折扣')
    unit_price     = models.FloatField('折后单价', help_text='折后单价')
    total_price = models.FloatField('折后总价', help_text='折后总价')
    #unit_price_weighted		= models.FloatField('加权后折后单价', help_text='加权后折后单价')	# 目前暂时不用
    #total_price_weighted	= models.FloatField('加权后折后总价', help_text='加权后折后总价')	# 目前暂时不用
    total_price_tracked		= models.FloatField('有效的投放额', help_text='有效的投放额', default=0)		# 有效的投放额度，即监测到的点击数>10的那些投放日的额度累加；=unit_price_weighted*ad_days_tracked
    discount_after_discount	= models.FloatField('折上折', help_text='折上折')		# 媒体购买的广告位的总价有时候会再打一个折扣（折上折）来到媒体总价，这种情况不多

    # statistic related info
    click 	= models.IntegerField('点击数', help_text='点击数', default=0) # FIX me with a function ...
    cpc		= models.FloatField('CPC', default=0)
    cpc_weighted	= models.FloatField('加权后CPC', default=0)		# 目前暂时不用
    start_day	= models.DateField(null=True, blank=True)	# 投放开始日
    end_day		= models.DateField(null=True, blank=True)	# 投放结束日

    DE_backend_url = models.TextField('后台URL', null=True, blank=True, help_text='后台URL')
    DE_campaign_id = models.IntegerField('DE_campaign_id')
    DE_flight_id = models.IntegerField('DE_flight_id', help_text='DE_flight_id')
    # DE_flight_number = models.SmallIntegerField('DE_flight_number', help_text='广告位在排期中的序列号')
    DE_ad_id = models.IntegerField('DE_ngAdID', help_text='DE_ngAdID')
    clickurl = models.CharField('目标网址', max_length=200, help_text='目标网址')
    
    unit_price_weighted = models.IntegerField('权重单价', help_text='分配权重后的单价')
    total_price_weighted = models.IntegerField('权重总价', help_text='分配权重后的总价')
    cpc_weighted = models.FloatField('权重CPC', default=0)
    
    class Meta:
        verbose_name = '广告位信息'
        verbose_name_plural = '广告位信息'
    
    def __unicode__(self):
        return "campaign:%s - %s - %s" % (self.DE_campaign_id, self.DE_ad_id, self.DE_flight_id)
    
    def is_end(self):
        """ if the flight ends ? compare with today """
        today = datetime.date.today()
        if (self.end_day - today).days >= 0:
            return False
        return True
    

class DE_ClickData(models.Model):
    ad		= models.ForeignKey(Ad, related_name='de_clickdata')
    media 	= models.ForeignKey(Media, related_name='de_clickdata')
    channel = models.ForeignKey(Channel, related_name='de_clickdata')
    media_ad_info = models.ForeignKey(MediaAdInfo, related_name='de_clickdata')
    flight      = models.ForeignKey(Flight, verbose_name='排期', help_text='排期', related_name='de_clickdata')
    cpm			= models.IntegerField('CPM', default=0) 	# 如果投放的单位为CPM，此字段用来记录该日的CPM投放量
    eventtype   = models.IntegerField('事件类型', help_text='事件类型', default=-1) # -1 means no type
    # 对于点击数<10的情况，可以认为是无效的数据；
    # 发生这种情况可能是因为：点击代码没有加到素材中；那几个零散的点击是测试时候记录到的；
    eventcount  = models.IntegerField('时间数量', help_text='事件数量', default=0)  # 0 means no data
    date        = models.DateField('事件日期', help_text='事件日期')
    # 对于在排期中计划的投放日，值为true，反之为false
    if_planned_spending		= models.BooleanField('是否计划投放', help_text='是否计划投放')

    class Meta:
        verbose_name = 'DE监测点击数据'
        verbose_name_plural = 'DE监测点击数据'

media_planning/forms.py
#! /usr/bin/env python
#coding=utf-8

from django import forms
from MediaChooser.media_planning.models import Flight
from MediaChooser.client.models import Client
from MediaChooser.misc.models import Industry
from MediaChooser.ad.models import ActivityType
from django.contrib.admin import widgets

class MP_SFlight_Form (forms.Form):

    campaign_id = forms.CharField()
    
class MP_MFlights_Form (forms.Form):
    
    campaign_name = forms.CharField(required=False)
    #industry = forms.ModelChoiceField(label='所属行业', queryset= Industry.objects.all())
    client = forms.ModelChoiceField(label='所属行业', required=False, queryset= Client.objects.all())
    activitytype = forms.ModelChoiceField(label='活动类型', required=False, queryset = ActivityType.objects.all())
    start_day = forms.DateField(label='开始日期', widget=widgets.AdminDateWidget, required=False)
    end_day = forms.DateField(label='结束日期', widget=widgets.AdminDateWidget, required=False)
    
class MP_MediaFilter_Form (forms.Form):
    
    start_day = forms.DateField(label='开始日期', widget=widgets.AdminDateWidget, required=False)
    end_day = forms.DateField(label='结束日期', widget=widgets.AdminDateWidget, required=False)
    
    

templates/media_planning/mp_upload.html
{% extends "ad_resource_mgmt/mp_base.html" %}

{% block sectionid %}mp_upload{% endblock %}

{% block rightpanel %}

    <div>
      <h2>上传排期</h2>
      <div id="div_upload">
	<form id="form_mp_upload" method="POST" action="" enctype="multipart/form-data">
		{% csrf_token %}
	  <p><label for="id_client">广告主: </label>
	    <select id="id_client" name="client">
	      <option value="" selected="selected">------</option>
	      {% for client in clients %}
	      <option value="{{ client.id }}">{{ client.c_name }}</option>
	      {% endfor %}
            </select>
	  </p>
	  <p><label for="id_activity_type">活动类型: </label>
	    <select id="id_activity_type" name="activity_type">
	      <option value="" selected="selected">------</option>
	      {% for type in activity_types %}
	      <option value="{{ type.id }}">{{ type.name }}</option>
	      {% endfor %}
	    </select>
	  </p>
	  <p><label for="id_file_upload">上传排期: </label><input type="file" id="id_file_upload" name="file_upload" /></p>
	  <p><label for="id_campaign">排期ID：</label><input type="text" id="id_campaign" name="campaign" /></p>
	  <p><label for="id_related_staff">相关负责人: </label>
	    <select id="id_related_staff" name="related_staff" multiple="multiple" size="6">
	      {% for st in staff %}
	      <option value="{{ st.id  }}">{% if st.last_name %}{{ st.last_name }}{{ st.first_name }}{% else %}{{ st.username }}{% endif %}</option>
	      {% endfor %}
	    </select>
	  </p>
	  <p><button type="submit">上传</button></p>
	</form>
	{% if ret.ret %}<p>返回信息: {{ ret.msg }}</p>
	{% else %}<p>返回信息: <span style="color:red; font-weight:bold;">{{ ret.msg }}</span></p>
	{% endif %}
      </div>
      <div id="div_recent_uploaded">
	  <h3>最近一周上传排期</h3>
	  <ul>
	  {% for ad in recent_uploaded %}
	  <li> <a href="{% url get_campaign ad.DE_campaign_id %}" title="{{ ad.name }}" >{{ ad.name }}</a> <br /> {{ ad.create_time|date:"Y/m/d H:i" }} by
	    {% if ad.uploader.last_name %}{{ ad.uploader.last_name }}{{ ad.uploader.first_name }}{% else %}{{ ad.uploader.username}}{% endif %}</li>
	  {% endfor %}
	  </ul>
      </div>
	
    </div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
  $("#form_mp_upload").validate({
    rules: {
      client: "required",
      activity_type: "required",
      mp: {required: true, number: true},
      file_up: "required",
      campaign: {required: true, number: true},
      related_staff: "required"
    },
    messages: {}
  });
});


</script>
{% endblock %}

templates/media_planning/my_uploads.html
{% extends "ad_resource_mgmt/mp_base.html" %}

{% block sectionid %}my_uploads{% endblock %}

{% block rightpanel %}

    <div>
      <h2>我上传的排期</h2>
      <div id="div_my_uploads">
	<ul>
	  {% for ad in uploads %}
	  <li> <a href="{% url get_campaign ad.DE_campaign_id %}" title="{{ ad.name }}" >{{ ad.name }}</a> <br />&nbsp;&nbsp;&nbsp;&nbsp;排期ID: {{ ad.DE_campaign_id }}&nbsp;&nbsp;&nbsp;&nbsp;上传时间: {{ ad.create_time|date:"Y/m/d H:i" }}
	  </li>
	  {% endfor %}
	</ul>
      </div>
	
    </div>

{% endblock %}

templates/media_planning/uploads_checkout.html
{% extends "ad_resource_mgmt/mp_base.html" %}

{% block sectionid %}uploads_checkout{% endblock %}

{% block rightpanel %}

    <div>
      <h2>排期上传查询</h2>
      <div id="div_upload">
	<form id="form_uploads_checkout" method="POST" action="" enctype="multipart/form-data">
	  {% csrf_token %}
	  <p><label for="id_uploader">上传者: </label>
	    <select id="id_uploader" name="uploader" >
	      <option value=""></option>
	      {% for st in uploaders %}
	      <option value="{{ st.id  }}" {% ifequal st.id uploader.id %} selected {% endifequal %} >
		{% if st.last_name %}{{ st.last_name }}{{ st.first_name }}{% else %}{{ st.username }}{% endif %}
	      </option>
	      {% endfor %}
	    </select>
	  </p>
	  <p><label for="id_start_day">开始日期：</label><input id="id_start_day" type="text" class="vDateField" name="start_day" size="10" /></p>
	  <p><label for="id_end_day">开始日期：</label><input id="id_end_day" type="text" class="vDateField" name="end_day" size="10" /></p>
	  <p><button type="submit">查询</button></p>
	</form>
      </div>
      <div id="div_recent_uploaded">
	{% if de_mp_dict %}
	<h3>需上传排期 {{ de_mp_dict|length }} 个，目前上传 {{ uploaded_num }} 个</h3>
	{% endif %}
      	<ul>
	  {% for key, value in de_mp_dict.items %}
	  <li> {{ key }} : {{ value }}
	  </li>
	  {% endfor %}
	</ul>
      </div>
    </div>

{% endblock %}

{% block js %}
<script type="text/javascript" src="/mc_media/js/jquery-ui-1.7.2.custom.min.js"></script>

<script type="text/javascript">

$(document).ready(function() {
  $("#form_uploads_checkout").validate({
    rules: {
      uploader: "required"
    },
    messages: {}
  });
  $("#id_start_day").datepicker();
  $('#id_start_day').datepicker('option', {dateFormat: 'yy-mm-dd'});
  $("#id_end_day").datepicker();
  $('#id_end_day').datepicker('option', {dateFormat: 'yy-mm-dd'});
});

</script>
{% endblock %}