ad_resource_mgmt/urls.py
#! /usr/bin/env python
#coding=utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('MediaChooser.ad_resource_mgmt.views',
    url(r'^$', 'query', name="query"),
    (r'^search/$', 'search'),
    
    (r'^query_mflights/$', 'query_mflights'),
    (r'^mflights/$', 'mflights'),
    (r'^query_media/$', 'query_media'),
    url(r'^campaign/(?P<campaign_id>\d+)/$', 'get_campaign', name='get_campaign'),
    url(r'^campaign/status/(?P<ad_id>\d+)/$', 'get_campaign_status', name='get_campaign_status'),
#    url(r'^campaign/(?P<campaign_id>\d+)/export/$', 'campaign_export', name='campaign_export'),
    url(r'^campaign_detail/(?P<campaign_id>\d+)/$', 'get_campaign_detail', name='get_campaign_detail'),
    url(r'^campaign_detail/(?P<campaign_id>\d+)/date_cpc/$', 'get_campaign_detail_date_cpc', name='get_campaign_detail_date_cpc'),
    url(r'^campaign_detail/(?P<campaign_id>\d+)/media_cpc/$', 'get_campaign_detail_media_cpc', name='get_campaign_detail_media_cpc'),
    url(r'^campaign_detail/(?P<campaign_id>\d+)/price_media/$', 'get_campaign_detail_price_media', name='get_campaign_detail_price_media'),
    url(r'^campaign_detail/(?P<campaign_id>\d+)/funnel/$', 'get_campaign_detail_funnel', name='get_campaign_detail_funnel'),
    url(r'^media_filter/$', 'media_filter', name="media_filter"),
    url(r'^media_reco/$', 'media_reco', name="media_reco"),
    
    (r'^get_mediatree/$', 'get_mediatree'),
    (r'^get_mediatree_chart/$', 'get_mediatree_chart'),
    url(r'^get_mediatree_chart_fusionchart/$', 'get_mediatree_chart_fusionchart', name='get_mediatree_chart_fusionchart'),
    (r'^get_mediareco/$', 'get_mediareco'),
    (r'^get_mediacats/$', 'get_mediacats'),
    url(r'^upload_creative/$', 'upload_creative', name="upload_creative"),
    url(r'^upload_creative/del/$', 'delete_upload_creative', name="delete_upload_creative"),
    url(r'^update_background_code/$', 'update_background_code', name="update_background_code"),
    (r'^media_reco/', 'media_reco'),
    (r'^change_flightname/', 'change_flightname'),
    url(r'^get_campaign_xls/(?P<campaign_id>\d+)/funel/', 'get_campaign_funel_xls', name='get_campaign_funel_xls'),
    url(r'^get_campaign_xls/(?P<campaign_id>\d+)/media_cpc/', 'get_campaign_media_cpc_xls', name='get_campaign_media_cpc_xls'),
    url(r'^get_campaign_xls/(?P<campaign_id>\d+)/media_price/', 'get_campaign_media_price_xls', name='get_campaign_media_price_xls'),
    url(r'^get_campaign_xls/(?P<campaign_id>\d+)/', 'get_campaign_xls', name='get_campaign_xls'),
    
    url(r'^chart_api/(?P<campaign_id>\d+)/(?P<chart_id>\w+)/', 'chart_api', name='get_chart_api'),
    url(r'^chart_api/image/export/', 'export_chart_image', name='export_chart_image'),
    
    
    #(r'^get_test_amdata/', 'get_test_amdata'),
    #(r'^get_test_amcolumn/', 'get_test_amcolumn'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
# Example:
# (r'^demo/', include('demo.foo.urls')),

# Uncomment the admin/doc line below and add 'django.contrib.admindocs'
# to INSTALLED_APPS to enable admin documentation:
# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

#url(r'^$', 'MediaChooser.ad_resource_mgmt.views.query', name="query"),
# Uncomment the next line to enable the admin:
(r'^', include('ad_resource_mgmt.urls')),
(r'^admin/(.*)', admin.site.root),
(r'^accounts/', include('registration.urls')),
(r'^weekly-report/', include('media_weekly_report.urls')),

(r'^client/', include('client.urls')),
(r'^media-planning/', include('media_planning.urls')),
(r'^media/', include('media.urls')),
(r'^pr/', include('pr.urls')),
#(r'^nielsen-media/', include('NielsenMedia.urls')),
#(r'^torres/', include('torres.urls')),

)

ad/models.py
#! /usr/bin/env python
#coding=utf-8

import datetime

from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User

from MediaChooser.media.models import Media, Channel
from MediaChooser.client.models import Client

EFFECTIVE_COUNT = 10
DC_CLICK_EVENTTYPE = 4

# 广告形式表
class AdType(models.Model):
    AD_CATEGORY_CHOICES = ((1, '硬广'),(2, '软广'),(3, '专题'),(4, '活动'),)

    category = models.PositiveSmallIntegerField('分类', choices=AD_CATEGORY_CHOICES, help_text='分类')
    c_name = models.CharField('中文名称', max_length=40, help_text='中文名称')
    e_name = models.CharField('英文名称', max_length=40, help_text='英文名称', blank=True, null=True)
    desc = models.TextField('描述', blank=True, null=True, help_text='描述')
    demo = models.FileField('演示', upload_to='files/', blank=True, null=True, help_text='演示')
    advantage = models.TextField('优势', blank=True, null=True, help_text='优势')
    disadvantage = models.TextField('劣势', blank=True, null=True, help_text='劣势')
    class Meta:
        verbose_name = '广告形式'
        verbose_name_plural = '广告形式'
    def __unicode__(self):
        return self.c_name

# 投放类型
class ActivityType(models.Model):
    name = models.CharField('名称', max_length=20, help_text='活动名称')
    desc = models.TextField('描述', null=True, blank=True, help_text='描述')

    class Meta:
        verbose_name = '活动类型'
        verbose_name_plural = '活动类型'
    
    def __unicode__(self):
        return self.name

class Ad(models.Model):
    client   = models.ForeignKey(Client, verbose_name='广告主')
    #adtype = models.ForeignKey(AdType, verbose_name='类型', related_name='related_adinfo')
    activity_type = models.ForeignKey(ActivityType)
    #product  = models.ForeignKey(Product)
    #minisite = models.ForeignKey(MiniSite)
    DE_campaign_id = models.IntegerField('campaign_id', unique=True, help_text='campaign_id')
    name  = models.CharField('name', help_text='name', max_length=256)

    # statistic related info
    spending	= models.IntegerField('投放费用', default=0)
    click		= models.IntegerField('DE记录到的点击数', default=0)
    cpc			= models.FloatField('CPC', default=0)

    #title = models.CharField('title', help_text='title', max_length=96)
    desc = models.TextField('desc', blank=True, null=True, help_text='desc')

    #targeting = models.DateField()
    uploader  = models.ForeignKey(User, verbose_name='上传者')
    start_day = models.DateField('开始日期', help_text='开始日期')
    end_day = models.DateField('结束日期', help_text='结束日期')
    create_time = models.DateTimeField('创建日期', auto_now_add=True, null=True, help_text='创建日期')
    last_modified = models.DateTimeField('最后修改', auto_now=True, null=True, help_text='最后修改')

    related_staff = models.ManyToManyField(User, related_name='ads', verbose_name='相关人员', through='AdRelatedStaff')
    ga_pid = models.CharField('GA profile id', blank=True, max_length=20)
    
    group_id = models.IntegerField('用户组', default=-1)
    
    date_range = []
    media = []
    date_price = {}
    date_click = {}
    
    has_init = False
    
    class Meta:
        verbose_name = 'Campaign'
        verbose_name_plural = 'Campaign'
                    
    def __unicode__ (self):
        return self.name
    
    def _init(self):
        self.date_range = []
        for n in range((self.end_day - self.start_day).days+1):
            date_str = str(self.start_day + datetime.timedelta(days=n))
            self.date_range.append(date_str)
            self.date_price[date_str] = 0
            self.date_click[date_str] = 0
        
        self.media = self._campaign_media()
        
    
    def _campaign_media(self):
        media = set()
        for f in self.flights.all():
            media.add(f.media.c_name)
        media_list = list(media)
        media_list.sort()
        return media_list
    
    def media_click(self):
        """ return sorted media click list during this campaign """
        media_click = {}
        flights = self.flights.all()
        for f in flights:
            if f.media.c_name in media_click:
                media_click[f.media.c_name] += f.click
            else:
                media_click[f.media.c_name] = f.click
        #return [ x[1] for x in sorted(media_click.iteritems(), key=lambda d:d[0])]
        return media_click
    
    def media_price(self):
        """ return sorted media price and tracked price list during this campaign """
        media_price = {}
        media_price_tracked = {}
        flights = self.flights.all()
        for f in flights:
            media_name = f.media.c_name
            if f.if_buy:
                if media_name in media_price:
                    media_price[media_name] += f.total_price * f.discount_after_discount
                else:
                    media_price[media_name] = f.total_price * f.discount_after_discount
                if media_name in media_price_tracked:
                    media_price_tracked[media_name] += f.total_price_tracked * f.discount_after_discount
                else:
                    media_price_tracked[media_name] = f.total_price_tracked * f.discount_after_discount
            else:
                if media_name not in media_price:
                    media_price[media_name] = 0
                if media_name not in media_price_tracked:
                    media_price_tracked[media_name] = 0
        #return [x[1] for x in sorted(media_price.iteritems(), key=lambda d:d[0])], [x[1] for x in sorted(media_price_tracked.iteritems(), key=lambda d:d[0])]
        return media_price, media_price_tracked
    
    def media_cpc(self):
        """ return sorted media cpc list during this campaign """
        media = self.media
        media_cpc = {}
        media_click = self.media_click()
        media_price = self.media_price()[1]
        #for i, m in enumerate(media):
        #    if media_click[i] != 0:
        #        media_cpc[i] = media_price[i] * 1.0 / media_click[i]
        #    else:
        #        media_cpc[i] = 0 
        
        for m in media_price:
            if media_click[m] != 0:
                media_cpc[m] = media_price[m] * 1.0 / media_click[m]
            else:
                media_cpc[m] = 0
        
        return media_cpc
        
    def daily_click(self):
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT date,sum(eventcount) FROM media_planning_de_clickdata \
            WHERE flight_id in %s and eventtype=%s and eventcount > %s\
            GROUP BY date ORDER BY date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            d = str(r[0])
            if d >= str(self.start_day) and d <= str(self.end_day):
                self.date_click[str(r[0])] = r[1]
        
        #return [x[1] for x in sorted(self.date_click.iteritems(), key=lambda d:d[0])]
        return self.date_click
        
    def daily_price(self):
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()        
        sql = "SELECT a.date,sum(b.unit_price * b.discount_after_discount) \
            FROM media_planning_de_clickdata a, media_planning_flight b \
            WHERE a.flight_id in %s AND a.if_planned_spending = true AND a.eventtype=%s AND a.eventcount > %s AND a.flight_id = b.id \
            AND b.if_buy = true GROUP BY a.date ORDER BY a.date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            self.date_price[str(r[0])] = r[1]
        
        #return [x[1] for x in sorted(self.date_price.iteritems(), key=lambda d:d[0])]
        return self.date_price
    
    def daily_cpc(self):
        daily_price = self.daily_price()
        daily_click = self.daily_click()
        #daily_cpc = [0] * len(self.date_range)
        daily_cpc = {}
        #for i in range(len(daily_cpc)):
        #    if daily_click[i] != 0:
        #        daily_cpc[i] = daily_price[i] / daily_click[i]
        #    else:
        #        daily_cpc[i] = 0
        for d in daily_click:
            if daily_click[d] != 0:
                daily_cpc[d] = daily_price[d] / daily_click[d]
            else:
                daily_cpc[d] = None
        return daily_cpc
    
    def media_daily_click(self):
        media_daily_click = {}
        flights = self.flights.all()
        fids = [ f.id for f in flights]
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT b.c_name, a.date, sum(eventcount) FROM media_planning_de_clickdata a, media_media b \
            WHERE flight_id in %s and eventtype=%s and eventcount > %s and a.media_id = b.id \
            GROUP BY b.c_name, date ORDER BY b.c_name, date" % (str(tuple(fids)), DC_CLICK_EVENTTYPE, EFFECTIVE_COUNT)
        cursor.execute(sql)
        rows = cursor.fetchall()
        for r in rows:
            media_name = r[0]
            date = r[1]
            click = r[2]
            
            if media_name in media_daily_click:
                media_daily_click[media_name][str(date)] = r[2]
            else:
                media_daily_click[media_name] = [0] * len(self.date_range)
        
        return media_daily_click
        #
    
    def campaign_detail(self):
        from django.db import connection
        cursor = connection.cursor()
        sql = "select b.c_name, d.c_name, c.adform, a.total_price * a.discount_after_discount, \
                a.click, a.if_buy, a.start_day, a.end_day, a.\"DE_ad_id\" \
                from media_planning_flight a, media_media b, media_mediaadinfo c, media_channel d \
                where a.media_id = b.id and a.ad_id =%s and c.id = a.media_ad_info_id and \

client/models.py
#! /usr/bin/env python
#coding=utf-8

from django.db import models
from MediaChooser.media.models import Media
from MediaChooser.misc.models import Industry
from django.contrib.auth.models import User

# 客户，特指andc客户，享受andc服务的大客户，包括levono等
class ClientManager (models.Manager):
    def get_clients_industry(self):
        industries = []
        #for c in super(ClientManager, self).get_query_set().all():
        for c in super(ClientManager, self).get_query_set().select_related('industry'):
            if c.industry != None and c.industry.c_name not in industries:
                industries.append(c.industry.c_name)
        return industries
    '''
    def get_clients_dict(self):
        clients_dict = {}
        for i in self.get_clients_industry():
            try:
                clients_dict[i]
            except KeyError:
                clients = Client.objects.filter(industry__c_name=i)
                clients_dict[i] = list(clients)
        return clients_dict
    '''
    
    def get_clients_dict(self):
        clients_dict = {}
        clients = Client.objects.select_related('industry')
        for c in clients:
            industry_name = c.industry
            if industry_name in clients_dict:
                clients_dict[industry_name].append(c)
            else:
                clients_dict[industry_name] = []
                clients_dict[industry_name].append(c)
        
        return clients_dict
    
    def get_clients_by_industry(self, id):
        try:
            industry = Industry.objects.get(pk=id)
            return super(ClientManager, self).get_query_set().filter(industry=industry)
        except ObjectDoesNotExist:
            return None

class Client(models.Model):
    c_name = models.CharField('客户名', max_length=128, unique=True, help_text='客户中文名称')
    e_name = models.CharField('客户名(英文)', max_length=128, help_text='客户英文名称')
    desc = models.TextField('描述', help_text='描述', blank=True, null=True)
    favor_media = models.ManyToManyField(Media, verbose_name='偏好媒体', help_text='客户偏好的媒体', blank=True, null=True)
    industry = models.ForeignKey(Industry, blank=True, null=True)
    objects = ClientManager()
    
    class Meta:
        verbose_name = '客户'
        verbose_name_plural = '客户'
    
    def __unicode__(self):
        return self.c_name
    
class DomainName(models.Model):
    client = models.ForeignKey(Client, null=True, blank=True, verbose_name=u'客户')
    business = models.ForeignKey(User, null=True, blank=True, verbose_name=u'营业')
    ip = models.CharField(u'地址', max_length=256, blank=True)
    domain_name = models.CharField(u'域名', max_length=256)
    path = models.CharField(u'存储路径', max_length=256, blank=True)
    parse_status = models.CharField(u'解析状态', max_length=256, blank=True)
    domain_name_register_info = models.CharField(u'域名注册信息', max_length=256, blank=True)
    domain_name_register_address = models.CharField(u'域名注册地址', max_length=256, blank=True)
    remark = models.CharField(u'备注', max_length=256, blank=True)
    
    class Meta:
        verbose_name = u'域名'
        verbose_name_plural = '域名'
        
    def __unicode__(self):
        return self.domain_name

templates/ad_resource_mgmt/error.html
{% extends "ad_resource_mgmt/mp_base.html" %}

{% block rightpanel %}

<h2>{{ message }}</h2>

<a href="javascript:window.history.back();">返回</a> 

{% endblock %}

templates/ad_resource_mgmt/mediacpc_detail.html
{% extends "ad_resource_mgmt/mp_detail_base.html" %}
{% load filters_extra %}
{% block uppanel %}
    <div>
        <div>媒体效果对比</div>
        <a title="导出excel文件" href="{% url get_campaign_media_cpc_xls campaign_id %}"><img src="/media-{{ request.path|first_subpath }}/images/icon_excel.gif" border=0 /></a>
        <div id="cpc_media_chart">
            You need to install or upgrade your flash player
        </div>
        <!--<div id="fcexpDiv" align="center">FusionCharts Export Handler Component</div>-->
    </div>        
{% endblock %}
{% block downpanel %}
    <div>
        <table id="mp_info">
            <tr>
                <td>媒体</td>
                <td>cpc</td>
                <td>click</td>
            </tr>
            {% for key, value in result.items %}
                <tr>
                    <td>{{ key }}</td>
                    {% for val in value %}
                    <td>{{ val }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>     
{% endblock %}
{% block js %}
    <script language="JavaScript" src="/media-{{ request.path|first_subpath }}/fusioncharts/js/FusionCharts.js"></script>   
    <script type="text/javascript" src="/media-{{ request.path|first_subpath }}/fusioncharts/js/FusionChartsExportComponent.js"></script> 
    <script type="text/javascript">
        $('document').ready(function(){
            var cpc_media_chart = new FusionCharts("/media-{{ request.path|first_subpath }}/fusioncharts/charts/MSCombiDY2D.swf", "myChartId", "80%", "400", "0", "0");
            cpc_media_chart.setJSONUrl("{% url get_chart_api campaign_id 'media_click_cpc_bar' %}");
            cpc_media_chart.render("cpc_media_chart");    
           // var myExportComponent = new FusionChartsExportObject("fcExporter1", "/media-{{ request.path|first_subpath }}/fusioncharts/charts/FCExporter.swf");
            //myExportComponent.Render("fcexpDiv");                      
        });
        
    </script>      
{% endblock %}

templates/ad_resource_mgmt/mp_detail_base.html
{% extends "ad_resource_mgmt/mp_base.html" %}
{% load filters_extra %}
{% block rightpanel %}
    <div>
        <a href="{% url get_campaign campaign_id %}">返回单排期效果页</a>
        <a href="{% url get_campaign_detail_date_cpc campaign_id %}">查看排期每日cpc走势</a>
        <a href="{% url get_campaign_detail_media_cpc campaign_id %}">查看媒体效果对比</a>
        <a href="{% url get_campaign_detail_price_media campaign_id %}">查看媒体投放量</a>
        <a href="{% url get_campaign_detail_funnel campaign_id %}">查看Convertion Ratio</a>
    </div>
    {% block uppanel %}
            
    {% endblock %}
    {% block downpanel %}
            
    {% endblock %}
            
{% endblock %}

templates/ad_resource_mgmt/mp_query.html
{% extends "ad_resource_mgmt/mp_base.html" %}

{% block sectionid %}mp_query{% endblock %}

{% block rightpanel %}

<h2>排期查询</h2>
<div class="div_query">
<!-- <form action="" method="post"> -->
	{{ form.campaign_id.errors }}<label for="id_campaign_id" title="DC里的排期ID">排期号: </label>{{ form.campaign_id }}{{msg}}
	<p class="p_query"><button id="campaign_id_submit">提交查询</button></p>
	<div style="clear: both;"></div>
<!-- </form> -->
</div>
<div id="dialog" title="错误" style="display:none">
	<p>
		<span class="ui-icon ui-icon-closethick" style="float:left; margin:0 7px 50px 0;"></span>
		您所查找的排期不存在.
	</p>
</div>
<div id="noperm_dialog" title="错误" style="display:none">
	<p>
		<span class="ui-icon ui-icon-closethick" style="float:left; margin:0 7px 50px 0;"></span>
		您没有权限查看此排期.
	</p>
</div>


<div class="div_query">
  <form action="query_mflights/" method="post">
    <table>
      <thead></thead>
      <tbody>
	<tr><td width="10%">{{ form_m.client.errors }}<label for="id_client">广告主: </label></td><td>{{ form_m.client }}</td></tr>
	<tr><td>{{ form_m.activitytype.errors }}<label for="id_activitytype">活动类型: </label></td><td>{{ form_m.activitytype }}</td></tr>
	<tr><td>{{ form_m.campaign_name.errors }}<label for="id_campaign_name">排期名: </label></td><td>{{ form_m.campaign_name }}</td></tr>
	<tr><td>{{ form_m.start_day.errors }}<label for="start_day">开始日期: </label></td><td>{{ form_m.start_day }}</td></tr>
	<tr><td>{{ form_m.end_day.errors }}<label for="end_day">结束日期: </label></td><td>{{ form_m.end_day }}</td></tr>
      </tbody>
    </table>
    <p class="p_query"><button id="campaign_name_submit">提交查询</button></p>
    <div style="clear: both;"></div>
	{% csrf_token %}
  </form>
</div>
<!-- <FORM METHOD="post" ACTION="query">form_flightschooser
	{{ form_flightschooser.industry.errors }}<label for="id_industry">所属行业: </label>
	{{ form_flightschooser.industry }}
	<p><input id="flightschooser_submit" type="submit" value="提交查询" /></p>
</FORM> -->
{% endblock %}


{% block js %}
<script type="text/javascript" src="/files_dl/js/jquery-ui-1.7.2.custom.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" type="text/css" media="all" />

<script type="text/javascript">
			
	$(document).ready(function(){
		$("#campaign_id_submit").click(function(){
			
			cid = $("#id_campaign_id").attr('value')

			if (cid == '')
			{
				alert('请输入排期id');
				return false;
			}
			
			path = location.pathname.split('/');
			//alert(location.pathname);
			path[path.length-1] = 'query';
			$.getJSON(location.pathname, {cid:cid}, function(data){
				if (data.url == false)
				{	
					$("#dialog").dialog({
						bgiframe: true,
						modal: true,
						resizable: false,
						buttons: {
							Ok: function() {
							$(this).dialog('destroy');
							}
						}
					});
				}
				else if (data.url == 'noperm'){
					$("#noperm_dialog").dialog({
						bgiframe: true,
						modal: true,
						resizable: false,
						buttons: {
							Ok: function() {
							$(this).dialog('destroy');
							}
						}
					});
				}
				else
				{	
					window.location = data.url;
				}
			},'json');
		});
		
		$("#id_start_day").datepicker();
		$('#id_start_day').datepicker('option', {dateFormat: 'yy-mm-dd'});
		$("#id_end_day").datepicker();
		$('#id_end_day').datepicker('option', {dateFormat: 'yy-mm-dd'});
		
		

		/*$("#campaign_name_submit").click(function(){
			
			if ($("#id_campaign_name").attr('value') == '')
			{
				alert('请输入排期名');
				return false;
			}
		});*/

	});

</script>
{% endblock %}

templates/ad_resource_mgmt/mp_upload.html
{% extends "base.html" %}

{% block extrahead %}

    <link href="/media/css/forms.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media_ldf/css/demos.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media_ldf/css/mc.css" rel="stylesheet" type="text/css" media="screen" />

    <script type="text/javascript" src="/media_ldf/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/media_ldf/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/media_ldf/js/jquery.validate.min.js"></script>

    <script type="text/javascript" src="../../admin/jsi18n/"></script>
    <script type="text/javascript" src="/media/js/core.js"></script>
    <script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/media/js/calendar.js"></script>
    <script type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>	

{% endblock %}

{% block sectionid %}mp_upload{% endblock %}

{% block columnwrap %}

    <div id="content-main">
        {% block content %}
	<form id="form_mp_upload" method="POST" action="" enctype="multipart/form-data">
		{% csrf_token %}
	  <p>上传排期</p>
	  <p><label for="id_client">广告主:</label>
	    <select id="id_client" name="client">
	      <option value="" selected="selected">------</option>
	      {% for client in clients %}
	      <option value="{{ client.id }}">{{ client.c_name }}</option>
	      {% endfor %}
            </select>
	  </p>
	  <p><label for="id_activity_type">活动类型:</label>
	    <select id="id_activity_type" name="activity_type">
	      <option value="" selected="selected">------</option>
	      {% for type in activity_types %}
	      <option value="{{ type.id }}">{{ type.name }}</option>
	      {% endfor %}
	    </select>
	  </p>
	  <p><label for="id_if_append">是否追加排期:</label>
	    <select id="id_if_append" name="if_append">
	      <option value="0" selected="selected">否</option>
	      <option value="1">是</option>
	    </select>
	  </p>
	  <p><label for="id_file_upload">上传排期:</label><input type="file" id="id_file_upload" name="file_upload" /></p>
	  <p><input type="submit" value="上传" /></p>
	</form>
	{{ ret }}
	{% for link in ret %}
	{{ link }}
	{% endfor %}
	{{ ret_len }}
	{{ test_wd }}
	{% endblock %}
    </div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
  $("#form_mp_upload").validate({
    rules: {
      client: "required",
      activity_type: "required",
      mp: {required: true, number: true},
      file_up: "required"
    },
    messages: {}
  });
});


</script>
{% endblock %}